//  _____                                 _                 _            
 /  __ \                               | |               | |           
 | /  \/  __ _  ___   ___  _   _  _ __ | |__    ___    __| |  ___  ___ 
 | |     / _` |/ __| / _ \| | | || '__|| '_ \  / _ \  / _` | / _ \/ __|
 | \__/\| (_| |\__ \|  __/| |_| || |   | | | || (_) || (_| ||  __/\__ \
  \____/ \__,_||___/ \___| \__, ||_|   |_| |_| \___/  \__,_| \___||___/
                            __/ |                                      
                           |___/                                       

  _____              _     
 |_   _|            | |    
   | |    ___   ___ | |__  
   | |   / _ \ / __|| '_ \ 
   | |  |  __/| (__ | | | |
   \_/   \___| \___||_| |_|
                           



services:
  - type: web
    name: CASEYRHODES-XMD
    env: node
    plan: free
    repo: https://github.com/caseyweb/CASEYRHODES-XMD
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false
